### ISSUE TITLE
'Exec format error' raised when calling spcomp

### ISSUE THREAD

**Issue by nosoop** [rumblefrog/setup-sp#7]
Regression introduced in v1.2.0; output from [this recently-ran workflow](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/runs/7226973302):

```
Checking for SourcePawn compiler...
Traceback (most recent call last):
  File "configure.py", line 158, in <module>
    available_version = misc.spcomp_util.extract_version(spcomp)
  File "/home/runner/work/SM-TFCustomAttributeStarterPack/SM-TFCustomAttributeStarterPack/misc/spcomp_util.py", line 11, in extract_version
    p = subprocess.Popen([spcomp], stdout=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/opt/hostedtoolcache/sourcepawn/1.10.6545/x64/spcomp'
Error: Process completed with exit code 1.
```
[Workflow corresponding to the failed run is available here.](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/blob/d5c69b2e37d159254141ddfde933b9c1be5aff9d/.github/workflows/build.yml)

Error gets thrown in [`spcomp_util.py`](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/blob/d5c69b2e37d159254141ddfde933b9c1be5aff9d/misc/spcomp_util.py); [`configure.py`](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/blob/d5c69b2e37d159254141ddfde933b9c1be5aff9d/configure.py#L153-L156) only checks for `spcomp`.  Not sure if v1.2.0 behaves properly if `spcomp64` is passed in; I'll report back once I have a workflow run on a different project that does do platform-specific paths.

**Comment by rumblefrog** [comment]
Hm, yeah, you should call `spcomp64_original` instead, the workaround may have broken your approach.

**Comment by nosoop** [comment]
Actually, would it be any trouble adding an optional input parameter named something like `no-proxy-script` that defaults to false?  `configure.py` can be run outside of a workflow, so having to modify it to call into a workaround specific to setup-sp seems awkward.
